export const jogadores = [
  {
    agilidade: 86,
    altura: 1.70,
    clube_atual: "Inter Miami",
    codigo_jogador: 1,
    drible: 95,
    forca: 68,
    foto: "imagem1.jpg",
    idade: 38,
    nacionalidade: "Argentina",
    nome: "Lionel Messi",
    peso: 72,
    posicao: "Ponta Direita",
    velocidade: 82
  },
  {
    agilidade: 88,
    altura: 1.87,
    clube_atual: "Al-Nassr",
    codigo_jogador: 2,
    drible: 89,
    forca: 85,
    foto: "imagem2.jpg",
    idade: 41,
    nacionalidade: "Portugal",
    nome: "Cristiano Ronaldo",
    peso: 83,
    posicao: "Centroavante",
    velocidade: 84
  },
  {
    agilidade: 92,
    altura: 1.75,
    clube_atual: "Santos",
    codigo_jogador: 3,
    drible: 94,
    forca: 62,
    foto: "imagem3.png",
    idade: 34,
    nacionalidade: "Brasil",
    nome: "Neymar Jr",
    peso: 68,
    posicao: "Ponta Esquerda",
    velocidade: 87
  },
  {
    agilidade: 90,
    altura: 1.80,
    clube_atual: "Real Madrid",
    codigo_jogador: 4,
    drible: 91,
    forca: 76,
    foto: "imagem4.jpg",
    idade: 26,
    nacionalidade: "França",
    nome: "Kylian Mbappe",
    peso: 75,
    posicao: "Atacante",
    velocidade: 97
  },
  {
    agilidade: 84,
    altura: 1.84,
    clube_atual: "Manchester City",
    codigo_jogador: 5,
    drible: 82,
    forca: 93,
    foto: "imagem5.png",
    idade: 25,
    nacionalidade: "Noruega",
    nome: "Erling Haaland",
    peso: 88,
    posicao: "Centroavante",
    velocidade: 89
  },
  {
    agilidade: 85,
    altura: 1.81,
    clube_atual: "Real Madrid",
    codigo_jogador: 6,
    drible: 90,
    forca: 72,
    foto: "imagem6.jpg",
    idade: 24,
    nacionalidade: "Brasil",
    nome: "Vinicius Junior",
    peso: 73,
    posicao: "Ponta Esquerda",
    velocidade: 95
  },
  {
    agilidade: 91,
    altura: 1.74,
    clube_atual: "Barcelona",
    codigo_jogador: 7,
    drible: 92,
    forca: 60,
    foto: "imagem7.png",
    idade: 18,
    nacionalidade: "Espanha",
    nome: "Lamine Yamal",
    peso: 66,
    posicao: "Ponta Direita",
    velocidade: 88
  },
  {
    agilidade: 83,
    altura: 1.88,
    clube_atual: "Bayern Munich",
    codigo_jogador: 8,
    drible: 84,
    forca: 82,
    foto: "imagem8.jpg",
    idade: 32,
    nacionalidade: "Inglaterra",
    nome: "Harry Kane",
    peso: 86,
    posicao: "Centroavante",
    velocidade: 74
  },
  {
    agilidade: 89,
    altura: 1.78,
    clube_atual: "Liverpool",
    codigo_jogador: 9,
    drible: 88,
    forca: 73,
    foto: "imagem9.png",
    idade: 33,
    nacionalidade: "Egito",
    nome: "Mohamed Salah",
    peso: 71,
    posicao: "Ponta Direita",
    velocidade: 90
  },
  {
    agilidade: 87,
    altura: 1.76,
    clube_atual: "Manchester City",
    codigo_jogador: 10,
    drible: 89,
    forca: 65,
    foto: "imagem10.jpg",
    idade: 31,
    nacionalidade: "Portugal",
    nome: "Bernardo Silva",
    peso: 64,
    posicao: "Meio-campo",
    velocidade: 78
  },
  {
    agilidade: 82,
    altura: 1.86,
    clube_atual: "Arsenal",
    codigo_jogador: 11,
    drible: 81,
    forca: 79,
    foto: "imagem11.png",
    idade: 26,
    nacionalidade: "Inglaterra",
    nome: "Declan Rice",
    peso: 80,
    posicao: "Volante",
    velocidade: 76
  },
  {
    agilidade: 88,
    altura: 1.72,
    clube_atual: "Tottenham",
    codigo_jogador: 12,
    drible: 87,
    forca: 69,
    foto: "imagem12.jpg",
    idade: 33,
    nacionalidade: "Coreia do Sul",
    nome: "Son Heung-min",
    peso: 72,
    posicao: "Atacante",
    velocidade: 89
  },
  {
    agilidade: 84,
    altura: 1.83,
    clube_atual: "Chelsea",
    codigo_jogador: 13,
    drible: 85,
    forca: 74,
    foto: "imagem13.png",
    idade: 24,
    nacionalidade: "Argentina",
    nome: "Enzo Fernandez",
    peso: 76,
    posicao: "Meio-campo",
    velocidade: 74
  },
  {
    agilidade: 90,
    altura: 1.71,
    clube_atual: "Barcelona",
    codigo_jogador: 14,
    drible: 93,
    forca: 58,
    foto: "imagem14.jpg",
    idade: 28,
    nacionalidade: "Brasil",
    nome: "Raphinha",
    peso: 68,
    posicao: "Ponta Direita",
    velocidade: 88
  },
  {
    agilidade: 79,
    altura: 1.93,
    clube_atual: "Liverpool",
    codigo_jogador: 15,
    drible: 74,
    forca: 90,
    foto: "imagem15.png",
    idade: 34,
    nacionalidade: "Países Baixos",
    nome: "Virgil van Dijk",
    peso: 92,
    posicao: "Zagueiro",
    velocidade: 78
  },
  {
    agilidade: 85,
    altura: 1.77,
    clube_atual: "PSG",
    codigo_jogador: 16,
    drible: 88,
    forca: 67,
    foto: "imagem16.jpg",
    idade: 24,
    nacionalidade: "Geórgia",
    nome: "Khvicha Kvaratskhelia",
    peso: 70,
    posicao: "Ponta Esquerda",
    velocidade: 84
  },
  {
    agilidade: 83,
    altura: 1.85,
    clube_atual: "Real Madrid",
    codigo_jogador: 17,
    drible: 86,
    forca: 78,
    foto: "imagem17.png",
    idade: 22,
    nacionalidade: "Inglaterra",
    nome: "Jude Bellingham",
    peso: 75,
    posicao: "Meio-campo",
    velocidade: 80
  },
  {
    agilidade: 87,
    altura: 1.79,
    clube_atual: "Barcelona",
    codigo_jogador: 18,
    drible: 89,
    forca: 63,
    foto: "imagem18.jpg",
    idade: 22,
    nacionalidade: "Espanha",
    nome: "Pedri",
    peso: 68,
    posicao: "Meio-campo",
    velocidade: 76
  },
  {
    agilidade: 86,
    altura: 1.80,
    clube_atual: "Manchester City",
    codigo_jogador: 19,
    drible: 87,
    forca: 77,
    foto: "imagem19.png",
    idade: 27,
    nacionalidade: "Espanha",
    nome: "Rodri",
    peso: 82,
    posicao: "Volante",
    velocidade: 72
  },
  {
    agilidade: 91,
    altura: 1.73,
    clube_atual: "Bayern Munich",
    codigo_jogador: 20,
    drible: 90,
    forca: 66,
    foto: "imagem20.jpg",
    idade: 22,
    nacionalidade: "Alemanha",
    nome: "Jamal Musiala",
    peso: 70,
    posicao: "Meia Ofensivo",
    velocidade: 86
  },
  {
    agilidade: 80,
    altura: 1.87,
    clube_atual: "Inter de Milão",
    codigo_jogador: 21,
    drible: 78,
    forca: 88,
    foto: "imagem21.png",
    idade: 28,
    nacionalidade: "Argentina",
    nome: "Lautaro Martinez",
    peso: 80,
    posicao: "Centroavante",
    velocidade: 82
  },
  {
    agilidade: 84,
    altura: 1.81,
    clube_atual: "Manchester United",
    codigo_jogador: 22,
    drible: 85,
    forca: 74,
    foto: "imagem22.jpg",
    idade: 27,
    nacionalidade: "Portugal",
    nome: "Bruno Fernandes",
    peso: 76,
    posicao: "Meia Ofensivo",
    velocidade: 75
  },
  {
    agilidade: 78,
    altura: 1.95,
    clube_atual: "Real Madrid",
    codigo_jogador: 23,
    drible: 71,
    forca: 91,
    foto: "imagem23.png",
    idade: 33,
    nacionalidade: "Bélgica",
    nome: "Thibaut Courtois",
    peso: 96,
    posicao: "Goleiro",
    velocidade: 55
  },
  {
    agilidade: 89,
    altura: 1.69,
    clube_atual: "Chelsea",
    codigo_jogador: 24,
    drible: 91,
    forca: 61,
    foto: "imagem24.jpg",
    idade: 24,
    nacionalidade: "Inglaterra",
    nome: "Cole Palmer",
    peso: 67,
    posicao: "Meia Ofensivo",
    velocidade: 79
  },
  {
    agilidade: 82,
    altura: 1.90,
    clube_atual: "Barcelona",
    codigo_jogador: 25,
    drible: 75,
    forca: 89,
    foto: "imagem25.png",
    idade: 27,
    nacionalidade: "Uruguai",
    nome: "Ronald Araujo",
    peso: 86,
    posicao: "Zagueiro",
    velocidade: 81
  },
  {
    agilidade: 87,
    altura: 1.76,
    clube_atual: "Napoli",
    codigo_jogador: 26,
    drible: 88,
    forca: 65,
    foto: "imagem26.jpg",
    idade: 25,
    nacionalidade: "Nigéria",
    nome: "Victor Osimhen",
    peso: 78,
    posicao: "Centroavante",
    velocidade: 90
  },
  {
    agilidade: 83,
    altura: 1.84,
    clube_atual: "Atlético de Madrid",
    codigo_jogador: 27,
    drible: 80,
    forca: 84,
    foto: "imagem27.png",
    idade: 26,
    nacionalidade: "França",
    nome: "Antoine Griezmann",
    peso: 73,
    posicao: "Segundo Atacante",
    velocidade: 78
  },
  {
    agilidade: 88,
    altura: 1.75,
    clube_atual: "Bayer Leverkusen",
    codigo_jogador: 28,
    drible: 89,
    forca: 66,
    foto: "imagem28.jpg",
    idade: 23,
    nacionalidade: "Alemanha",
    nome: "Florian Wirtz",
    peso: 70,
    posicao: "Meia Ofensivo",
    velocidade: 82
  },
  {
    agilidade: 86,
    altura: 1.78,
    clube_atual: "Milan",
    codigo_jogador: 29,
    drible: 87,
    forca: 70,
    foto: "imagem29.png",
    idade: 27,
    nacionalidade: "Portugal",
    nome: "Rafael Leao",
    peso: 81,
    posicao: "Ponta Esquerda",
    velocidade: 93
  },
  {
    agilidade: 84,
    altura: 1.82,
    clube_atual: "Juventus",
    codigo_jogador: 30,
    drible: 83,
    forca: 75,
    foto: "imagem30.jpg",
    idade: 25,
    nacionalidade: "Sérvia",
    nome: "Dusan Vlahovic",
    peso: 84,
    posicao: "Centroavante",
    velocidade: 79
  }
];


export const banners = [
  './images/banner0.jpg', 
  './images/banner1.jpg', 
  './images/banner2.jpg',
  './images/banner3.jpg',
  './images/banner4.jpg',
  './images/banner5.jpg',
  './images/banner6.jpg',
  './images/banner7.jpg',
  './images/banner8.jpg'
];
